version: "3.7"
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  #Airflow settings
  - AIRFLOW_HOME=/opt/airflow
  - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
  - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
  - AIRFLOW__CELERY__REUSLT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTION=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__METRICS__STATSD_HOST=statsd_exporter
  - AIRFLOW__METRICS__STATSD_ON=True
  - AIRFLOW__METRICS__STATSD_PORT=9125
  # - AIRFLOW__CORE__STORE_DAG_CORE=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  # - AIRFLOW__WEBSERVER_RBAC=False
  - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
  # Movielens settings.
  # - AIRFLOW_CONN_MOVIELENS=http://airflow:airflow@movielens
  # - MOVIELENS_USER=airflow
  # - MOVIELENS_PASSWORD=airflow
  # - MOVIELENS_HOST=http://movielens:5000
x-airflow-image: &airflow_image apache/airflow:2.7.3-python3.8
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  init:
    image: *airflow_image
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'

  webserver:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver

  scheduler:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: scheduler

  # docker-compose -f docker-compose-celeryexecutor.yml --scale worker=3 -d
  worker:
    image: *airflow_image
    restart: always
    depends_on:
      - scheduler
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    environment: *airflow_environment
    command: celery worker

  flower:
    image: *airflow_image
    restart: always
    depends_on:
      - worker
    ports:
      - "5555:5555"
    environment: *airflow_environment
    command: celery flower

  statsd_exporter:
    image: prom/statsd-exporter:v0.18.0
    restart: always
    volumes:
      - ./files/statsd_mapping.yml:/tmp/statsd_mapping.yml
    ports:
      - "9102:9102"
      - "9125:9125/udp"
    command: --statsd.mapping-config=/tmp/statsd_mapping.yml

  prometheus:
    image: prom/prometheus:v2.22.0
    restart: always
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # In grafana : http://host.docker.internal:9090
    command:
      - --web.enable-admin-api
      - --web.enable-lifecycle
      # Flags below are defaults, but must be added explicitly, otherwise would be overridden by flags above
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

  grafana:
    image: grafana/grafana:7.2.1
    restart: always
    ports:
      - "3000:3000"

  redis:
    image: redis:5-alpine

  redis_exporter:
    image: oliver006/redis_exporter:v1.5.2-alpine
    ports:
      - "9121:9121"
    command: --redis.addr=redis://redis:6379

#networks:
#  airflow:
#    name: airflow

volumes:
  logs:
    name: chapter12_celeryworker_integration