init:
  build:
    context: docker/airflow-data
    args:
      AIRFLOW_BASE_IMAGE: *airflow_image
  image: manning-airflow/airflow-data
  depends_on:
    - postgres
  environment: *airflow_environment
  entrypoint: /bin/bash
  command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
webserver:
  build:
    context: docker/airflow-data
    args:
      AIRFLOW_BASE_IMAGE: *airflow_image
  image: manning-airflow/airflow-data
  restart: always
  depends_on:
    -postgres
  ports:
    - "8080:8080"
  volumes:
    - logs:/opt/airflow/logs
  environment: *airflow_environment
  command: webserver
scheduler:
  build:
    context: docker/airflow-data
    args:
      AIRFLOW_BASE_IMAGE: *airflow_image
  image: manning-airflow/airflow-data
  restart: always
  depends_on:
    - postgres
  volumes:
    - ./dag:/opt/airflow/dags
    - logs:/opt/airflow/logs
    -  data:/data
  environment: *airflow_environment
  command: scheduler
events_api:
  build: ./docker/events-api
  image: manning-airflow/events-api
  ports:
    - "5000:5000"

volumes:
  data:
  logs: